### ISSUE TITLE
Notification System Wanted 

### ISSUE THREAD

**Issue by tylerstraub** [seriousbears/seriousbears#6]
The single most pressing enhancement request by group opinion /poll is a notification feature for when a DJ goes live.

Roadmap item will consist of a manual based (BEARCOMMAND) method.. followed by automated solution using Bearfunction's liquidsoap configuration and RESTful API.

Notification types for the first iteration (by order of importance):
- Twitter (External Subscription)
- Email (Internal Subscription)

**Comment by nullfunction** [comment]
I'm envisioning two RESTful endpoints for this:

http://www.seriousbears.net/MetadataPush
http://www.seriousbears.net/DJNotification

I'll push a JSON object with the metadata that I have to the first, and when there's a status change (a DJ connects to the staging stream, a DJ goes live, or a DJ disconnects) I'll push that info to the second.

For metadata, the only fields that I'm currently handling are:
- Artist
- Title
- Album
- TrackNumber
- Genre
- Date
- Website

I wanted to be able to handle a comment field, and am planning on doing this eventually, but the ID3v2 spec around comments is super wonky, so the simplified ID3 handler in mutagen does not implement comments and I'll have to write a custom handler.

I will send you the fields that I have for a given item. If I do not have a date, for example, I will not pass the date key at all, rather than passing a blank value.

For the DJ Notification, today I can do connects/disconnects, and am looking into how to send a message when the transition to a live stream happens -- that is, when the DJ cuts over from the staging stream to live. The data will probably be in a format similar to this:

`{ "Status": "<Status>, "DJ": "<DJ Name> }`

Where Status can be any of these values: OnAir (DJ is live on the stream), Staging (DJ is connected but has not gone live), OffAir (DJ has disconnected)

The front end will be responsible for debouncing if there are stream drops and reconnects. That is, you probably want to start a timer once you get a disconnect, and if you don't see a reconnect within _x_ seconds, treat it as if the DJ is done broadcasting. Otherwise, we may see weird behavior if a DJ has a bad connection.
